version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
    volumes:
      - ./build/reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
  api:
    container_name: api
    tty: true
    build: ./build/go/
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/api
    depends_on:
      - reverseproxy
