version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
    volumes:
      - ./build/reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./build/reverseproxy/log:/var/log/nginx
    depends_on:
      - api
  api:
    container_name: api
    tty: true
    build: ./build/go/
    expose:
      - 80
    volumes:
      - ./api:/go/src/api
