version: "3"
services:
  reverseproxy:
    image: nginx:1.25.4
    container_name: reverseproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./build/reverseproxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./build/reverseproxy/log:/var/log/nginx
      - ./build/key/fib-api.com-key.pem:/etc/certs/fib-api.com-key.pem
      - ./build/key/fib-api.com.pem:/etc/certs/fib-api.com.pem
    depends_on:
      - api
  api:
    container_name: api
    tty: true
    build: ./build/go/
    expose:
      - 80
    environment:
      PORT: 80
    volumes:
      - ./api:/go/src/api
